[package]
name = "portfolia"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14"
askama-derive-axum = "0.1"
axum = { version = "0.8", features = ["macros"] }
shuttle-axum = "0.56"
shuttle-runtime = { version = "0.56", features = ["tracing-subscriber"] }
tokio = "1.47"
tower-http = { version = "0.6", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
markdown = "1.0.0"
glob = "0.3.1"
lazy_static = "1.4.0"

