/*
title = "Electrostatics"

date = 2022-01-18



[taxonomies]

categories = ["Physics"]

tags = ["Physics"]
*/

What is electricity, and how does it work?

== Electrons
<electrons>
Fundamentally, the negative charge comes from the #strong[electron], a subatomic particle. The positive charge comes from #strong[protons], also in the atom. The unit of the charge is the #strong[Coulomb] ($C$). An electron has a charge of $- 1.60 times 10^(- 16) C$, and a proton has the same charge but positive. However, the proton is much heavier than an electron, being about 1836 times as massive. This means that electrons are easy to displace, which is why their movement is the fundamental concept behind electricity.

The way that electric charge is generated is by rubbing two materials together in a way that transfers electrons between the two. For example, if you rub your clothes against a shag carpet, it will transfer electrons to your clothes.

#emph[However, charge is neither created nor destroyed, due to the law of conservation of electric charge!]

As you might already know from playing around with magnets, like charges repel and unlike charges attract each other. This attraction is known as the #strong[electrostatic force].

== Conductors/Insulators
<conductorsinsulators>
Electric charge is not limited to its power to attract and repel. It can also move through objects; this is how electricity travels from power plants to your house, through wires. Not all materials are created equal in their ability to #strong[conduct] electricity through them. Those that conduct poorly are called electrical #strong[insulators] and those that can well are called electrical #strong[conductors]. This material property is typically related to how easily valence electrons can move around in the molecules of the material.

== Charging by Contact/Induction
<charging-by-contactinduction>
I said before that electrical charge can be generated by rubbing, for example against a shag carpet. This is known as #strong[charging by contact]. However, this is not the only way to charge an object. As we know, electrons can be attracted and repelled. If a negatively charged object is brought close to a neutrally charged object, the electrons in the neutrally charged object will be repelled to the other side, changing the distribution of charge in the object. This is known as #strong[charging by induction] because the electrons are induced by the charge to move.

This effect will disappear when the inducing object leaves, unless we introduce #strong[grounding]. A grounding wire is a way to disappear free electrons from a charged object. Typically, an object is wired to a large diffuse object such as the earth, so free electrons will leave the small object forever. In the example I used above, if there is a grounding wire attached to the other side where the electrons were repelled to, then those electrons would "disappear". After the inducing object leaves, the formerly neutral object would become positively charged.

This can even occur in materials like plastic which are insulating. Although the free electrons cannot move as in materials like metals, positive charges can still be induced towards the surface, allowing for a surface positive charge that negatively charged objects to stick to.

== Coulomb's Law
<coulombs-law>
#strong[The magnitude $F$ of the electrostatic force exerted by one point charge $q_1$ on another point charge $q_2$ is directly proportional to the magnitudes $\|q_1\|$ and $\|q_2\|$ of the charges and inversely proportional to the square of the distance $r$ between them:]

$ F = k frac(\|q_1\|\|q_2\|, r^2) $

#strong[where $k$ is a proportionality constant: $k = 8.99 times 10^9 N dot.op m^2\/C^2$ in SI units.]

So what does this law mean? Crucially, this law gives no mention of direction. The magnitude of the force is the same regardless of whether the charges attract or repel, so we don't need to worry about that.

#quote(block: true)[
The constant $k$ is sometimes written as $k = 1\/\(4 pi epsilon.alt_0\)$ where $epsilon.alt_0$ is the #emph[permittivity of free space] with the value $8.85 times 10^(- 12) C^2\/N dot.op m^2$.
]

A Coulomb is an absolutely massive amount of charge that is typically only found in situations like lightning. It is far more common to encounter microcoulombs expressed as $mu C$ which are $10^(- 6) C$.

This is a situation that is expressed between only two point charges. What happens when we have multiple point charges? We have to calculate the #emph[vector sum] of all these forces.

This is easiest when all the charges are in a line, as this is simply a matter of adding and subtracting the forces depending on whether they are attractive or negative. We must calculate Coulomb's law for each pair and then combine those as appropriate.

When we have points on a plane, things get a little more complicated. The easiest way to handle this is by separating each force into its $x$ and $y$ components. Pick one point to be set at the angle 0° degrees with respect to the point we are calculating for, then set the $theta$ for each other point with respect to that line. Then, get $F_x$ and $F_y$ through $cos theta$ and $sin theta$, respectively. The point with 0° will only have an $x$ component.

Then, once you have the $F_x$ and $F_y$ all parcelled out according to positives and negatives, get the total $F$ by applying the Pythagorean theorem to them. The answer $theta$ is given by $tan^(- 1) F_y / F_x$.

== The Electric Field
<the-electric-field>
We have so far been talking about how individual point charges affect other point charges. When we talk about an entire system of charges, we need a broader, high-level understanding of charge. For that purpose, #strong[the electric field] is essential. Fundamentally, the electric field is defined as the electric force per coulomb $arrow(E) = arrow(F)\/q_0$. This calculation pretends that we have a small positive #emph[test charge] $q_0$ placed in the middle of this electric field, which is affected by the various charges to have a force pointing a direction. This test charge typically has a small magnitude so as not to disturb the surrounding field.

The electric field is independent of whatever point charge it's affecting. We could imagine a field with a magnitude $2.0 N\/C$ and direction upwards that causes a positive charge to go in the same direction as it, but a negative charge to go in the opposite direction. We can calculate the magnitude for each point charge with $F =\|q_0\|E$.

Electric fields, just like forces, are vectors. When we add fields together, we must equally be mindful of $E_x$ and $E_y$.

An electric field is composed of multiple point charges. The amount of electric field that an individual point charge $q$ produces is expressed by the equation

$ E = frac(k\|q\|, r^2) $

Notice how $q_0$ the test charge is not included in this equation. Since this new equation only expresses magnitude, we must individually determine direction by the sign of the charge. If $q$ is positive, $arrow(E)$ is directed in the opposite direction of $q$, and vice versa for negative.

An additionally useful equation relates to #strong[parallel plate capacitors]. These are two parallel plates of opposite charge that have an electric field directed from the positive plate to the negative plate. The equation for this electric field is

$ E = frac(q, epsilon.alt_0 A) = sigma / epsilon.alt_0 $

As you can see in this equation, the symbol $sigma$ denotes $q\/A$ and is sometimes called #emph[charge density]. Importantly, the distance between the plates is actually totally irrelevant to the electric field, unlike with point charges.

== Electric Field Lines
<electric-field-lines>
It is often useful to draw fields as a set of lines directed out of or towards a point charge. #strong[#emph[In general, electric field lines are always directed away from positive charges and toward negative charges.]]

For convenience, we usually only draw them in two dimensions, though technically charges act in three dimensions. The number of lines is expressed as proportional the magnitude of the charge, so five times as many lines for five times the magnitude. In general, the electric field is stronger when lines are closer together, which is why parallel plate capacitors have the same electric field in the middle but bulge out at the ends.

The lines are not always straight, as in the case of an #strong[electric dipole]. An electric dipole has two separated point charges of opposite signs and equal magnitude. The field lines in this case come from the positive charges and curve towards the negative charge, getting faster as they get closer. The electric field vector in this case is #emph[tangent] to the electric field at any point. Between two charges of the same sign, there is practically no electric field because the lines curve away from each other.

== Shielding
<shielding>
Electric fields can exist anywhere where electrons can move freely, which includes the inside of a conductor. It's a logical conclusion: electrons hate being near each other, so they try to get away in the conductor. That leaves them all at the surface of the conductor. The same principle applies for positive charges; conductors generally have all their excess charge at their surface.

However, since all the excess charge is at the surface, that means that in the interior of the conductor, there is no movement of free electrons because they're not there. This means that there is #emph[zero] electric field inside a conductor.

If we imagine a conductor within a parallel plate capacitor, there is a lot of electric field going on. However, all of the charges are directed outside of it. Inside the conductor, any charge is completely shielded from the intense electric field outside the conductor.

== Gauss' Law
<gauss-law>
We have so far discussed electric fields created by point charges. In fact, an electric field is often composed by multiple charges that are spread out, also known as a #emph[charge distribution]. Understanding an electric field created by a charge distribution is significantly more complex and requires understanding #strong[electric flux].

We can think of flux on a high level as similar to a vector, with a direction and magnitude, but with the additional dimension of area. This concept will be important when discussing magnets.

We can consider the formula for a point charge as a special form of #strong[Gauss' Law] which describes electric fields in general. Remember how we can substitute $1\/\(4 pi epsilon.alt_0\)$ for $k$? This means that our new equation is $E = q\/4\(pi epsilon.alt_0 r^2\)$. If we multiply both sides by $A$ which is $4 pi r^2$ for a sphere, then we get

$ E A = q / epsilon.alt_0 $

where $E A$ is electric flux, also known as $Phi_E$.

However, we don't always have a nice, neat distribution of charge like in a sphere. A Gaussian surface can be arbitrarily shaped. We have to think of this similarly to how we think about integrals in calculus. If we take an arbitrarily small area $Delta A$, it has an electric field that is essentially constant in magnitude and direction. The surface has a #emph[normal] which is a line perpendicular to the surface. The angle $phi$ is between the electric field vector and the normal. With all these variables, Gauss' Law is expressed as so:

#strong[The electric flux $Phi_E$ through a Gaussian surface is equal to the net charge $Q$ enclosed by the surface divided by $epsilon.alt_0$, the permittivity of free space:]

$ Sigma\(E cos phi\)Delta A = Q / epsilon.alt_0 $

#strong[with the left side being $Phi_E$ in $N dot.op m^2\/C$.]

The flux has the same sign as $Q$.
