/*
title = 'Martingales and Random Walks'
date = 2024-09-19
source = 'FE-610 | Stochastic Calculus'
source_date_basis = "Meeting date verified against the personal Academics calendar."
instructor = 'Thomas Lonon'
term = 'Fall 2024'
[taxonomies]
categories = ['Stochastic Calculus']
tags = ['Stochastic Calculus', 'Martingales', 'Random Walks']
*/

== Week 2
<week-2>
=== Lecture Notes
<lecture-notes>
==== Measurability
<measurability>
\(continuing from last time)

A #strong[stochastic process] is a collection of random variables indexed by time. If you start out at time 0 and each time you pick heads you go one step, it's now a walk. You have no idea where you're going to be in the future, but you know the general distribution and have an idea of where you're likely to do.

We also have a filtration which is a collection of $sigma$-algebras indexed by time. If we have enough information in the filtration to know what set your outcome is in, you get an #strong[adapted stochastic process]. Mathematically, these variables are considered $cal(F)$-measurable by the filtration $cal(F)$.

==== Independence
<independence>
Two $sigma$-algebras are independent if for every element $A$ and $B$ in both $sigma$-algebras:

$bb(P)\(A inter B\)= bb(P)\(A\)times bb(P)\(B\)$

This is a strong mathematical result, but it is not useful because most useful $sigma$-algebras are infinite.

BUt if you can show that the joint cdf is the same as the products of the marginal cdfs (WILL COVER LATER) it will do the same thing.

We can say that two random variables are independent if the $sigma$-algebras generated by them are

One useful way to do this is by determining that if one variable is measurable by a $sigma$-algebra that is independent of a $sigma$-algebra generated by another variable, they are independent.

==== Variance
<variance>
Variance $bb(V)\(X\)$ is defined by:

$V a r\(X\)= bb(V)\(X\)= bb(E)\[\(X - bb(E)\[X\]\)^2\]= bb(E)\[X^2\]-\(bb(E)\[X\]\)^2$

This variable is #strong[necessarily nonnegative], although it may be infinite. If your variance is negative, it is for sure wrong. The standard deviation of $X$ is the square root of the variance.

The reason that it's squared is that it's always positive, which means that movements above the mean matter as much as movements below the mean. The reason it's squared and not absolute value is that if you have tiny differences from the mean, and you square them, they disappear, while bigger ones get bigger. It minimizes tiny differences and maximizes larger ones. This is why it's called the #strong[measurement of central tendency], because it measures how clustered values are around the mean.

==== Covariance
<covariance>
We have a sample space and we take variables. You measure how much variables fluctuate with each other with respect to the inputs from the sample space.

$"Cov"\(X\,Y\)= bb(E) {\(X - bb(E)\[X\]\)\(Y - bb(E)\[Y\]\)}$

$= sum_(omega in Omega)\(X\(omega\)- bb(E)\[X\]\)\(Y\(omega\)- bb(E)\[Y\]\)bb(P)\(omega\)$

You're going through every entry and seeing how much $X$ differs from its mean and $Y$ differs from its mean, weighting them with their probability measure. It's how they are different from each other #emph[in the same scenario].

We can say that two variables are uncorrelated if their covariance is 0. Independent variables are uncorrelated, but uncorrelated variables may not be independent. The value of covariance doesn't tell you how correlated variables are, only the correlation coefficient does:

$rho\(X\,Y\)= frac("Cov"\(X\,Y\), sqrt(bb(V)\(X\)bb(V)\(Y\)))$

If this value is 0, then they are uncorrelated. This coefficient is always $\[- 1\,1\]$. -1 means perfectly inverse, and 1 means perfectly direct. This only has to do with direction, not necessarily magnitude.

Let's consider a probability space. $cal(G)$ is a sub-$sigma$-algebra of $cal(F)$, and $X$ random variable. The #strong[conditional expectation] of $X$ given $cal(G)$ is a random variable that is measurable i.e.~$bb(E)\[X\|cal(G)\]$ is $cal(G)$-measurable and partial averaging

If i limited myself just to a set $A$ and I averaged $X$ over $A$, I should get the same result as if I took the average of $X$. Underneath this subset, if I average over the $X$ terms.

#emph[Conditional expectations are random variables].

Technically, the condition in a conditional expectation is a $sigma$-algebra.

Important theorems:

+ Linearity of conditional expectations: $bb(E)\[c_1 X + c_2 Y\|cal(G)\]= c_1 bb(E)\[X\|cal(G)\]+ c_2 bb(E)\[Y\|cal(G)\]$ Let's consider a situation where $X$ can take one of two values and $Y$ can take one of two values, both dependent on $a\,b\,c\,d$. If $Y = 3$, $omega in { a\,c }$, then $bb(E)\[X\|Y = 3\]= sum_(omega in Omega) X\(omega\)bb(P)\(omega\|Y = 3\)$ and this is the same as $sum_(omega in Omega) X\(omega\)frac(bb(P)\(omega inter { a\,c }\), bb(P)\({ a\,c }\))$ from Bayes theorem Knowing that Y=3, that means $sum_(omega in { a\,c }) X\(omega\)frac(bb(P)\(omega\), 2\/3)$ $= 3 / 2\(X\(a\)bb(P)\(a\)+ X\(c\)bb(P)\(c\)\)$
+ We can take something that is known outside of an expectation. $bb(E)\[X Y\|cal(G)\]= X bb(E)\[Y\|cal(G)\]$
+ Iterated conditioning. If $cal(H) subset cal(G)$, (think of this as information), then we know less information in $cal(H)$ than in $cal(G)$. If I create a new random variable around $X$ when you condition it just on this less information set, you get: $bb(E)\[bb(E)\[X\|cal(G)\]\|cal(H)\]= bb(E)\[X\|cal(H)\]$ We use iterated conditioning to complicate a process before simplifying it.
+ Independence: If $X$ is independent of $cal(G)$, having the condition doesn't do anything.
+ Conditional Jensen's Inequality - not important

==== Martingale Processes
<martingale-processes>
Consider an adapted stochastic process $M\(t\)$, for $0 lt.eq t lt.eq T$ where $T$ is a fixed positive number. The process needs to be such that if I know all the information up to time $s$, my best estimate for where it will be in the future, it will be the same as it is now. On average, I expect it to stay the same. Even though it probably won't, I expect it to. If you expect it to grow, it's a submartingale, and if you expect it to shrink, it's a supermartingale.

==== Markov
<markov>
If you have a stochastic process where for every non-negative function $f$ on the number line, there is another $g$ where you can describe the expectation for a future $f\(X\(t\)\)$ given the information in time $s$ with $g\(X\(s\)\)$. How much information do we need to calculate the value of this process? We would love to have a stock process that is Markov. This aligns with the idea that all past information is encoded in the current price, so we only need the current price and some function on that to determine a future price.

==== Random Walks
<random-walks>
We can define the outcomes of the tosses of a coin where heads is 1, and tails is -1. The process of flipping a coin and calculating the sum of the values is the #strong[symmetric random walk] $M$. These increments are independent from each other, whether symmetric or asymmetric. Knowing that there were a bunch of heads in the past doesn't give you any information about future flips. Our increment is defined by:

$M_(k_(i + 1)) - M_(k_i) = sum_(j = k_i + 1)^(k_(i + 1)) X_j$

This starts at plus 1 because… wasn't listening 😓

If we want to calculate the expected value of this, we can use the linearity of expectation to bring the expectation into the random variable: $sum_(i = k_i + 1)^(k_(i + 1)) bb(E)\[X_i\]$

By adding these together, we can see that the expectation of the random variable is 0.

Is variance a linear operator? If it is, then $"Var"\(alpha X + beta Y\)= alpha "Var"\(X\)+ beta "Var"\(Y\)$

Using our definition of variance, this is the same as

$bb(E)\[\(alpha X + beta Y\)^2\]- bb(E)\[alpha X + beta Y\]^2$

$= alpha^2 bb(E)\[X^2\]+ 2 alpha beta bb(E)\[X Y\]+ beta^2 bb(E)\[Y^2\]- alpha^2 bb(E)\[X\]^2- 2 alpha beta bb(E)\[X\]bb(E)\[Y\]- beta^2 bb(E)\[Y\]^2$

and this ends up equalling, once you cancel everything out

$= alpha^2 "Var"\(X\)+ 2 alpha beta "Cov"\(X\,Y\)+ beta^2 "Var"\(Y\)$

Clearly, this is not a linear operator. Only in the scenario where the variables are independent and their coefficient is 1, i.e.~they are independent and identically distributed (iid), do they act as if they are linear.

When we look at the random walk $M$, we can see that each increment of the random walk is independent, and the coefficient is 1. So in this case, the summation of the variances happens to equal the variance of the summations.

What about $bb(E)\[X_j^2\]$? Because the negative outcome is squared, it becomes 1, which means that the variance is 1, so that the summation of variances is $l - k$. If you have a walk that lasts 5 steps or 500 steps, the expectation is the same, but the variance goes from 5 to 500.

We can prove this symmetric random walk is a Martingale.

We need to prove for $k < l$ that

$bb(E)\[M\(l\)\|cal(F)\(k\)\]= M\(k\)$

If we add a zero, nothing should happen, right?

$= bb(E)\[M\(l\)- M\(k\)+ M\(k\)\|cal(F)\(k\)\]$

Now we can use the linearity of expectations to take out the $M\(k\)$

$bb(E)\[M\(l\)- M\(k\)\|cal(F)\(k\)\]+ bb(E)\[M\(k\)\|cal(F)\(k\)\]$

for the purposes of this, $cal(F)\(k\)$ is the information we would know at time $k$, and $M\(k\)$ is definitely known with respect to that information. We also know that the difference between $M$ is the increment, and that the increment is independent of information, so we can ignore it:

$bb(E)\[M\(l\)- M\(k\)\]+ M\(k\)$

We already know that the expectation of the increment is 0, so

$M\(k\)= M\(k\)$

==== First Order Variation
<first-order-variation>
This is the total change of the process. The first order variation in a function is the change in the y-axis. We'll consider $Pi$ as the partition of the process, going from ${ t_0\,t_1\,dots.h\,t_n }$, where this is a sequence of ordered values that ends at $t$. Let's get an operator called the norm which gives you the length of the biggest piece of the partition: $\|\|Pi\|\|$

We want a brute force way to calculate this first order variation for any function. We'll cut up our function into a bunch of different pieces, and then look at the value of the function at every point (the "realizations" of this process). You can get all the changes in y at the different values and add them all up. In order to get the true value, we would add more and more points, maybe an infinite number of points. We need to take the limit as the norm of the partition approaches 0. The mechanical way to do this is to take the norm and cut it in half at every step:

$F V_T\(f\)= lim_(\|\|Pi\|\|arrow.r 0) sum_(j = 0)^(n - 1)\|f\(t_(j + 1)\)- f\(t_j\)\|$

For a continuous and differentiable function, we can use the mean value theorem which means that for every increment, there exists a number which exists within that increment where the derivative of that point is equal to the slope between the beginning and end of the increment. In this case, we can use this fact to simplify this to get the Riemann integral.

==== Quadratic Variation
<quadratic-variation>
$\[f\,f\]\(T\)= lim_(\|\|Pi\|\|arrow.r 0) sum_(j = 0)^(n - 1)\(f\(t_(j + 1)\)- f\(t_j\)\)^2$

Does not have a nice real world analogy. It is that same change squared. This is uninteresting outside of stochastic calculus because the quadratic variation for a continuous, differentiable function is always 0.

We can create a handy inequality here. We can take out the norm like this and say

$lim_(\|\|Pi\|\|arrow.r 0)\|\|Pi\|\|sum_(j = 0)^(n - 1)\(f'\(t_j^(*)\)\)^2\(t_(j + 1) - t_j\)$

is greater than or equal to the same but with the difference squared, because the norm is the largest piece.

And because this is a continuously shrinking limit that's being added together, we can say that this is an integral of a derivative. But we also know that because the term of the norm is here, that goes to 0, which means that the entire thing is 0. And because that is greater than or equal to the quadratic variation formula, that must also always be zero (because it has to be positive).

We will deal with some situations where the first order variation will be infinite, and quadratic variation will give us a more interesting result.

The random walk evolves in a discontinuous, non-differentiable way. It also is random, so there are multiple different versions of the same function. Subdividing this function with first order variation gives you that the expectation is 0 most of the time. We can consider it as

$F V_4\(M\)= sum_(j = 1)^4\|X_j\|$

so you get the total change as being 4. #strong[Open question:] explain this step more clearly.

For quadratic order variation, this is

$\[M\,M\]\(4\)= sum_(j = 1)^4\(X_j\)^2= 4$

This does not necessarily occur! If the step size changed to 2 and -1, this is no longer true. The quadratic order variation is only the same as first order variation when the random walk is symmetric.

==== Scaled Symmetric Random Walk
<scaled-symmetric-random-walk>
#strong[Brownian motion] is an approximation for a process that constantly fluctuates. Our random walk jumps up and down simplistically. We need to start taking steps a lot more often, but the problem with that is it would significantly magnify our variation without changing much. We also need to decrease step size. We create more and more steps by subdividing the x-axis, and make them smaller. This gives us our #strong[scaled symmetric random walk]. We will take $n$ times as many steps, but the step size is decreased by $sqrt(n)$:

$W^(\(n\))\(t\)= 1 / sqrt(n) sum_(j = 1)^(n t) X_j$

We still have independence of increments in this walk. The expected value of a walk is still 0. We can use the same arguments to determine that this is a martingale. But if we look at the variance of the increments in the scaled symmetric random walk, it is now

$"Var" (sum_(j = n s + 1)^(n t) 1 / sqrt(n) X_j)$

This presents a problem for our attempt to convert between summation of variances because there is now a coefficient. But because $alpha = beta$ in this case, #strong[Open question:] explain this conversion more clearly.

$= sum_(j = n s + 1)^(n t) 1 / n "Var"\(X_j\)$

$= 1 / n\(n t - n s\)= t - s$

The reason it has to be $sqrt(n)$ and not $n$ is because in this formula, the variance would be going to 0 as $n$ goes to $oo$.

The quadratic variation becomes $t$, but the first order variation goes to $oo$.

==== Normal Distribution
<normal-distribution>
We will prove that the scaled symmetric walk approaches the normal distribution. Any normal variable is defined by $mu$ and $sigma^2$. It also has a

$phi_(W^(\(n\))\(t\))\(s\)= bb(E)\[e^(s W^(\(n\))\(t\))\]$

$= bb(E)\[e^(sum_(j = 1)^(n t) s / sqrt(n) X_j)\]$

$= bb(E) [product_(j = 1)^(n t) e^(s / sqrt(n) X_j)]$

This is the expected value of the product as a whole bunch of independent variables, which means that it's the same as the product of the expectations:

$= product_(j = 1)^(n t) bb(E) [e^(s / sqrt(n) X_j)]$

Important: understand what's random and what's not. $X_j$ only is random. Given the expectation of $X_j$ being known:

$= product_(j = 1)^(n t) (1 / 2 e^(s / sqrt(n)) + 1 / 2 e^(- s / sqrt(n)))$

this is the same as

$= (1 / 2 e^(s\/sqrt(n)) + 1 / 2 e^(- s\/sqrt(n)))^(n t)$

This is the moment generating function

We are trying to prove that

$lim_(n arrow.r oo) phi_(W^(\(n\))\(t\))\(s\)= e^(1 / 2 s^2 t)$

because this means that the walk is normally distributed. We can take the natural log of both sides

$lim_(n arrow.r oo) log (phi_(W^(\(n\))\(t\)) \( s \)) = 1 / 2 s^2 t$

Let's make a convenience variable $x$

$x = 1 / sqrt(n)$

We are satisfied that the limit of $n$ going to $oo$ is the same as $x$ going to 0.

$lim_(x arrow.r 0^(+))\(t / x^2 log\(1 / 2 e^(s x) + 1 / 2 e^(- s x)\)\)$

this results in a 0/0, which is undesirable. In order to get rid of this situation, we will apply L'Hopital's rule.

$=^L frac(s t, 2) lim_(x arrow.r 0^(+))\(frac(1 / 2 e^(s x) - 1 / 2 e^(- s x), x)\)$

which is still indeterminate, so we will apply it once again, which will give us the normal distribution

#strong[Open question:] copy the limiting argument from the video.

==== Brownian Motion
<brownian-motion>
Suppose there is a continuous function $W\(t\)$ which starts at $W\(0\)= 0$ and depends on $omega$. We have increments that are independent and each of the increments are normally distributed. The expectation is 0, and the variation is $t_(i + 1) - t_i$. The quadratic variation of Brownian motion is known to be $t$. Because this is a continuous, non-differentiable variable, its first order variation goes to infinity.

Let's talk about mean squared convergence. We can define a random process that will converge to our quadratic variation, and if its square does as well, and the mean of that square converges as well, the expectation must as well.

We have a sample quadratic variation for a random partition

$Q_Pi = sum_(j = 0)^(n - 1)\(w\(t_(j + 1)\)- W\(t_j\)\)^2$

We will make more intricate partitions as we go on so that the limit approaches 0.

I want to show that

$lim_(\|\|Pi\|\|arrow.r 0) bb(E)\[Q_Pi\]= bb(E)\[T\]$

where $T$ is a constant. Because $T$ is a constant, expectation is itself and variance is 0. We can then show that we want $Q_Pi$ to approach both the variance and the value of $T$.

$bb(E)\[Q_Pi\]= bb(E)\[sum_(j = 0)^(n - 1)\(W\(t_(j + 1)\)- W\(t_j\)\)^2\]$

We can use the linearity of expectation to get

$= sum_(j = 0)^(n - 1) bb(E)\[\(W\(t_(j + 1)\)- W\(t_j\)\)^2\]$

Using our previous definition of variance as

$bb(E)\[X^2\]= "Var"\(X\)+ bb(E)\[X\]^2$

We know that the mean of the increment of Brownian motion is 0 and its variation is time $t$.

So this becomes

$sum_(j = 0)^(n + 1)\(t_(j + 1) - t_j\)= t$

therefore,

$lim_(\|\|Pi\|\|arrow.r 0) bb(E)\[Q_Pi\]= t$

because the limit of a constant is the same as the constant.

$"Var"\(\(W\(t_(j + 1)\)- W\(t_j\)\)^2\)= bb(E)\[\(W\(t_(j + 1)\)- W\(t_j\)\)^4\]$

Without standardization, the fourth moment is $3 sigma^4$

The variance of an increment is the duration of time.

$lim_(parallel Pi parallel arrow.r 0) "Var"\(Q_Pi\)= 2 lim_(parallel Pi parallel arrow.r 0) sum_j\(t_(j + 1) - t_j\)^2= 0$

We have derived the quadratic variation of time. 🤯

Time is a continuous, differentiable function, so it's 0.

Overall: we have determined that the quadratic variation of Brownian motion is equal to the time #emph[almost surely], since any individual continuous differentiable function formed by Brownian motion has probability 0 of occurring.
