/*
title = 'Probability Spaces and Filtrations'
date = 2024-09-12
source = 'FE-610 | Stochastic Calculus'
source_date_basis = "Meeting date verified against the personal Academics calendar."
instructor = 'Thomas Lonon'
term = 'Fall 2024'
[taxonomies]
categories = ['Stochastic Calculus']
tags = ['Stochastic Calculus', 'Filtrations', 'Measure Theory']
*/

== Week 1
<week-1>
=== Readings
<readings>
==== General Probability Theory
<general-probability-theory>
===== Infinite Probability Spaces
<infinite-probability-spaces>
Let's define an infinite probability space $Omega_oo$. This sample space is uncountably infinite, which means that the probability of any particular outcome is zero. Therefore, in order to determine the probability of an event, we define the formula for the probability of certain simple events, then use probability measures to determine the probability of more complicated events.

$sigma$-algebras form the basis of these simple events: $ E x p l a n a t i o n o f\(sigma\)- a l g e b r a s f o u n d i n L e c t u r e N o t e s $

===== Lebesgue Measures
<lebesgue-measures>
The probability of picking a number in between ⅓ and ⅔ is ⅔ - ⅓ = ⅓. This is also true for open intervals because the probability of an individual point occurring is 0.

We can apply $sigma$-algebras to the Lebesgue measure by generating a $sigma$-algebra from the collection of all closed intervals in our interval, like:

$\[0\,1 / 3\]\,\[1 / 2\,1\]\,\[1 / 4\,230 / 243\]$

and so on. Open intervals can be defined as a union of a sequence of closed intervals, so these are included as well. The $sigma$-algebra generated by this process is the #strong[Borel $sigma$-algebra], specifically of the subset $\[0\,1\]$, which is $cal(B)\[0\,1\]$. The Borel $sigma$-algebra is a well-defined set of events (remember, an event is a set) where the outcome is a real number. In this context, under the rules of $sigma$-algebras, an event is an interval, a union of intervals, a complement of an interval, or any combination of these.

===== Coin Tosses
<coin-tosses>
Let's think about coin tosses. Through #strong[filtration] (see notes), we can define the probability of every event that can be described as a finite number of coin tosses. We can determine the probability of every individual sequence in $Omega_oo$ by showing that their probabilities converge to zero since they are fractions that multiply together infinitely.

We can use the rules of $sigma$-algebras and probability measures to determine the probability of each of these events, like how the probability measure of the union of disjoint events (remember, events are sets) is equivalent to the summation of the probability measures of each event.

There are some events that are not easily computed unless we define them in this respect. Consider

$lim_(n arrow.r oo) frac(H_n\(omega_1 dots.h omega_n\), n) = 1 / 2$

which describes all sequences of tosses where the long-run probability of choosing heads is ½. This set must be in $cal(F)_oo$ so we can determine its probability measure. If we choose positive integers $m$ and $n$, we can define

$A_(n\,m) = { omega\;\|frac(H_n\(omega_1 dots.h omega_n\), n) - 1 / 2\|lt.eq 1 / m }$

where this set is in $cal(F)_n$ i.e.~that step in the filtration. We can define this as a combination of sets if we recognize that for each threshold $m$, there is an $N$ where for all $n$ after $N$ i.e.~for all sufficiently long sequences after a certain point, the average of the sequence meets the threshold, following the definition of a limit. By considering intersections as "all of these are true" and unions as "at least one must be true", we can define this as

$A = inter.big_(m = 1)^oo union.big_(N = 1)^oo inter.big_(n = N)^oo A_(n\,m)$

By using the law of large numbers (large enough sequences will converge to the true value), we can see that $bb(P)\(A\)= 1$ for probability of ½, i.e.~that the probability of an outcome belonging to this set is 1

Note here that this is not the same thing as saying that every outcome occurs in this set. We can easily imagine outcomes that do not. However, any individual event has a probability of 0 of occurring, so all those exceptional events together have a probability of 0. The way we describe this technically is that the event corresponding to the set with probability measure of 1 occurs #strong[almost surely].

===== Random Variables and Distributions
<random-variables-and-distributions>
Let's define a random variable in the context of all this measure theory. We'll generalize the random variable to a function $X$ with the property that (in probability space $\(Omega\,cal(F)\,bb(P)\)$

${ X in B } = { omega in Omega\;X\(omega\)in B }$

where $B$ is a Borel subset of $bb(R)$, this subset of $Omega$ is in $sigma$-algebra $cal(F)$. Essentially, this defines $X$ as a function mapping outcome $omega$ to a Borel subset i.e.~an interval or combination of intervals on the real number line. This is the formal way to turn probability measures into actual numbers (see dice example from lecture notes).

We are not interested in $X$ taking a specific value as that will typically be 0, so we will usually talk about the probability that $X in B$.

===== Stock Prices
<stock-prices>
Let's consider the binomial asset pricing model where $S_0\(omega\)= 4$, $u = 2$, and $d = 1\/2$ , which is generalized as

i.e.~the stock price doubles on heads and halves on tails. Let's think of the probability of the stock price now as the distribution of mass. $S_0 = 4$ occurs with probability one, so this random variable has a unit of mass on 4. If we move two step forwards, $bb(P) { S_2 = 16 } = p^2$, $bb(P) { S_2 = 4 } = 2 p q$ and $bb(P) { S_2 = 1 } = q^2$, where $p$ and $q$ are the probabilities of $u$ and $d$, respectively. There are three lumps of mass distributed between 16, 4, and 1, each with the size of their probabilities. Now let's think of spreading that mass continuously. The distribution of a random variable is about the amount of mass in a set. This distribution measure $mu_X$ of random variable $X$ is a probability measure $P$, but it is done on $B$ rather than subsets of $Omega$. In other words, it measures the probability of $X$ being in a particular Borel subset.

Random variables have distributions, but they are not the same thing. The variable is the mapping between the outcome and the real number line i.e.~a function, and the distribution is a measure of the probability that the variable is a certain value, or more generally, in a certain Borel subset. A random variable can have two different distributions and two different random variables can have the same distribution. Consider $bb(P)$ as the uniform measure of $\[0\,1\]$. We have two random variables $X\(omega\)= omega$ and $Y\(omega\)= 1 - omega$. The distribution measure of $X$ is uniform, which means that all outcomes are equally likely. The distribution measure of $Y$ is also uniform, despite being different from $X$, they're both $b - a$.

Now instead let's define $bb(P)$ as

$bb(P)\[a\,b\]= integral_a^b 2 omega d omega = b^2 - a^2\,0 lt.eq a lt.eq b lt.eq 1$

This is still a probability measure on $\[0\,1\]$ because $bb(P)\[0\,1\]= 1$. If you take a Borel subset of this interval, you can calculate its probability measure through the properties of probability measures applied to each interval that is unioned or complemented.

The distribution measure is one way to record a distribution. The other is the #strong[cumulative distribution function] $c d f$

$F\(x\)= bb(P) { X lt.eq x }\,x in bb(R)$

The difference is that distribution measure is a direct mapping of the idea of probability measure onto the Borel subset, while the cdf is a distribution measure on the specific Borel subset $mu_X\(- oo\,x\]$. It can also be converted backwards as $mu_X\(x\,y\]= F\(y\)- F\(x\)$

Through the rules of probability measures, when the distribution measure is determined for every interval $\[a\,b\]$ in $bb(R)$, then it is determined for every Borel subset of $bb(R)$.

We can also get more detail on the distribution in two special functions.

We can have a #strong[density function] $f\(x\)$

$mu_X\[a\,b\]= bb(P) { a lt.eq X lt.eq b } = integral_a^b f\(x\)d x$

which describes the distribution through its integral.

The #strong[probability mass function] tells us that a random variable $X$ takes one of the values in a particular sequence with probability 1. You could imagine, for instance, if $X = omega^2$, there is a probability of 1 that $X$ is one of the values in the sequence of squared numbers. Strictly, this is defined where $p_i = bb(P) { X = x_i }$ and $sum_i p_i = 1$.

The sequence of numbers $x_1\,x_2\,dots.h$ is a Borel subset.

Random variables can be described by a density, a probability mass function, both, or neither. This last one is very advanced.

Let's define the #strong[standard normal density]:

$phi\(x\)= 1 / sqrt(2 pi) e^(- x^2 / 2)$

and the #strong[cumulative normal distribution function] as

$N\(x\)= integral_(- oo)^x phi\(xi\)thin d xi$

This function is strictly increasing and maps $bb(R)$ to $\(0\,1\)$ and has a strictly increasing inverse function $N^(- 1)\(y\)$. Let's consider the uniformly distributed random variable $Y$ on probability space $\(Omega\,cal(F)\,bb(P)\)$, and $X = N^(- 1)\(Y\)$.

The distribution measure is the probability measure that $X\(omega\)$ is in the interval defined. The distribution measure of $Y omega$ therefore is $\(N\(a\)\,N\(b\)$, which means that the distribution measure is $N\(b\)- N\(a\)$ because $Y$ is uniformly distributed, which is the same as

$integral_a^b phi\(x\)d x$.

This distribution measure $mu_X$ is known as the #strong[standard normal distribution], and any random variable with this distribution is a #strong[standard normal random variable]. This technique of generating a standard normal random variable is called the #strong[probability integral transform] and it is essential to Monte Carlo simulation.

A simpler way to get a standard normal random variable is to take this integral from arbitrary $a$ and $b$ as a probability measure for the random variable $X\(omega\)= omega$. This method works for any distribution, but it is not useful when we have multiple random variables with their own distributions and dependencies. For those cases we need a single probability space.

===== Expectation
<expectation>
We are interested in computing an "average value" of $X$ in a probability space. For a finite $Omega$, this is trivially:

$bb(E) X = sum_(omega in Omega) X\(omega\)bb(P)\(omega\)$

The same can be done for a countably infinite $Omega$.

However, if $Omega$ is uncountably infinite, expectation must be defined as an integral.

First, let's consider the Riemann integral. This involves partitioning the area under the function in ever smaller subintervals and adding them up, which gets closer and closer to the true integral. There is an upper Riemann sum based on the maximum of the areas and lower based on the minimum, which both converge to the Riemann integral.

The reason we can't use the Riemann integral for expectation is that our x-axis is $Omega$, which is not necessarily a subset of $bb(R)$. We instead must partition the y-axis.

We have defined this as a Lebesgue sum, which is the sum of

=== Lecture Notes
<lecture-notes>
==== $sigma$-algebras
<sigma-algebras>
The set of possible outcomes is the sample space $Omega$. If you flip a coin, the sample space is ${ H\,T }$

We are interested in the probability of events, which might be more complicated than an outcome. A $sigma$-algebra is a set of elements that belong to $cal(F)$ the powerset of $Omega$. The empty set must belong to it, all complements of sets must belong there, and the unions of all the composite sets must also belong there.

The $sigma$-algebra MUST contain $nothing$ and $Omega$, and this particular algebra is called the #strong[trivial $sigma$-algebra] because it is the simplest possible one. This might be confusing because $sigma$ can represent both the standard deviation and the algebra, so use your brain for context.

A fancier $sigma$-algebra could be generated from a set $A$ contained in it, which would be $sigma\(B\)= { nothing\,A\,Omega\,A^c }$

Trick question: if I have a set $B$, what is it? It's actually the same just with $B$

A different question is $sigma\(A\,B\)$. This would start with generators ${ nothing\,Omega\,A\,B\,A^c\,B^c\,A union B\,\(A union B\)^c}$

The number of elements in $sigma$-algebra can be found as 2 to the power of the number of distinct regions. For disjoint $A$ and $B$, this is 3.

What about joint $A$ and $B$ like a Venn diagram. There's the area outside of $A$ and $B$, the area just in $A$, the area just in $B$, and the area shared by $A$ and $B$, so 4, which means 16 elements.

$sigma\(A\,B\)= { nothing\,Omega\,A\,B\,A^c\,B^c\,A union B\,\(A union B\)^c\,$

$A union B^c\,\(A union B^c\)^c= A^c inter B = B\\A\,B union A^c\,\(B union A^c\)^c= A\\B\,A^c union B^c\,\(A^c union B^c\)^c= A inter B\,$

$((B union A^c)^c) union ((A union B^c)^c)}$

#strong[Open question:] draw out a venn diagram of what each of these mean

Let's say we choose some random person at Stevens. Event A is undergraduate students, Event B is graduate students. Some people are neither (professors) and some people are both (accelerated students). The $sigma$-algebra expresses the event space.

==== Probability Measure
<probability-measure>
The function mapping $cal(F)$ maps all of the sets in our $sigma$-algebra to events in the event space, which we can use for the probability measure $bb(P)$. We have two axioms:

+ $bb(P)\(Omega\)= 1$
+ the $bb(P)$ of a sequence of disjoint sets is equal to the sum of the

The #strong[probability space] is the combination of the sample space, function mapping, and probability measure: $\(Omega\,cal(F)\,bb(P)\)$

If $bb(P)\(A\)= 1$, then the event $A$ occurs almost surely. Doesn't mean it can't happen, but it has zero probability of occurring.

Example: If I were to pick a completely random real number between 0 and 1, the probability I would pick a rational number is 0, even though there clearly are rational numbers that exist.

A random variable is a function $X$ that maps from the event space to all real numbers $bb(R)$. You've been doing this your whole life without knowing it. Roll a six-sided die. What's the sample space? It's not 1, 2, 3, 4, 5, 6, it's a set of weird looking symbols that we #emph[map onto] numbers. You could equally create a $Y$ which says 6, 7, 8, 9, 10, 11.

The Borel subsets are every possible subdivision of the number line. It's essentially a way to describe the real number line through set theory.

==== Expectation
<expectation-1>
Regular expectation is the probability of each outcome added together. How can you be certain that you're exhaustive? We have to define elements in our sample space, and we use set theory to derive this:

$bb(E)\[X\]= sum_(omega in Omega) X\(omega\)bb(P)\(omega\)$

This looks like regular expectation, but it can be extended to understand the expectation of a function on a random variable as well.

Assume we have a fair coin. $X\(omega\)$ is 1 if $omega$ is heads, 0 if tails. $Y\(omega\)$ is 10 and -2 for the same.

What is $bb(E)\(X\)$? $sum_(omega in Omega) X\(omega\)bb(P)\(omega\)= X\(h\)bb(P)\(h\)+ X\(t\)bb(P)\(t\)= 1 * 0.5 + 0 * 0.5 = 0.5$

Let's think more advanced:

$bb(E)\[e^x\]= bb(E)\[g\(x\)\]= sum_(omega in Omega) g\(X\)$

Expected value are linear operators, so $bb(E)\[alpha X + beta Y\]= alpha bb(E)\[X\]+ beta bb(E)\[Y\]$ this is very useful for operations

Jensen's inequality mainly communicates that Variance is never negative: if $phi$ is a convex real-valued function and if $bb(E)\[X\]< oo$, then

$phi\(bb(E)\[X\]\)< = bb(E)\[phi\(X\)\]$

Probability being greater than 1 and variance being negative are massive red flags that should stop you in your tracks.

==== Change of Measure
<change-of-measure>
We can shift between probability spaces and get different probability measures like so:

$Z\(omega\)= frac(tilde(bb(P))\(omega\), bb(P)\(omega\))$

this is random variable which is almost surely nonnegative with $bb(E)\[Z\]= 1$.

new function:

$tilde(bb(P))\(A\)= integral_A Z\(omega\)d bb(P)\(omega\)$

so $tilde(bb(P))$ is a probability measure.

We could consider the same thing for $Omega$ as the set instead of $A$, but the integral of $Z$ with respect to the probability measure over the sample space is just the same thing as $bb(E)\[Z\]$, which is axiomatically 1.

$v bb(E)\[X Z\]= integral_Omega X\(omega\)$

We know from the definition of $Z$ as the ratio of probability measure that $Z\(omega\)d bb(P)\(omega\)= d tilde(bb(P))$ which gives us our integral over $Omega$ and $bb(E)\[Z\]$

==== Equivalent Measure
<equivalent-measure>
Equivalent probability measures only need to agree on which sets in $cal(F)$ have probability zero. Let's say we've bent a coin so much that now landing on heads has a 10% chance. The event space is still heads and tails, but the probability measure is different because the probability of the heads event and the tail event are different. Yet, these are still equivalent because they agree that the only set with probability zero is $nothing$.

Let's say you're drawing a card from a deck and checking the suit. If you remove some cards, there's still an equivalent probability measure. But if you remove all the clubs, it is not equivalent.

#strong[Radon-Nikodým derivative] #strong[Open question:] add this from slides

==== Filtration
<filtration>
A #strong[filtration] is a collection of $sigma$-algebras where each one contains all the previous ones, like Russian nesting dolls. The best way to think about them is information that accrues over time at each step.

If we have random variable $X$, the $sigma$-algebra generated by $X$ is $sigma\(X\)$, which is the collection of all subsets of $Omega$ where $\(X in B\)$ for $B$ Borel subset #strong[Open question:] look up this up more formally.

Flipping a coin:

$Omega = { omega_1\,omega_2\,omega_3 : omega_i in { h\,t } }$

Before we even flip a coin, what do we know we would know about the coin flip? It's either heads or tails.

$cal(F)\(1\)= { nothing\,Omega\,H\,T }$

What if we flip it twice? We have four distinct outcomes now, HH, HT, TH, and TT.

$cal(F)\(2\)= { nothing\,Omega\,H H\,H T\,T H\,T T\,H H^c\,H T^c\,T H^c\,T T^c\,H H union H T\,H H union T H\,H H union T T\,H T union T H\,H T union T T\,T H union T T }$

What about three times? 😅

$cal(F)\(3\)= { nothing\,Omega\,dots.h }$ (256 elements)

==== Measurability
<measurability>
If $cal(G)$ is also a $sigma$-algebra, and every set in $sigma\(X\)$ is in $cal(G)$, then $X$ is said to be $cal(G)$-measurable. If we have

$Omega = { a\,b\,c\,d }$,

and $X\(omega\)$ 2 if a, 0, if b or c, -2 if d

and $Y\(omega\)$ 13 if a or b, -2 if c or d

and $Z\(omega\)$ -2 if a or d, 3 if b or c

What is $sigma\(Z\)$? In order to generate a $sigma$-algebra from a random variable, we look at the partitions in the function and add those into the generator:

$sigma\(Z\)= { nothing\,Omega\,{ a\,d }\,{ b\,c } }$

We can also more easily define these sets as $alpha$, $beta$, $gamma$, etc. to simplify writing down.

We can see that $X$ is $Z$-measurable. But what does that actually mean?

Let's say I know $X = 2$. I do know the values of $Y$ and $Z$, because the outcome has to be $a$.

But if $X$ is 0, I have no idea what $Y$ is. I do know what $Z$ is.
