/*
title = 'Probability Spaces'
date = 2024-09-02
source = 'FE-540 | Probability Theory'
source_date_basis = "Meeting date verified against the personal Academics calendar."
instructor = 'Zhenyu Cui'
term = 'Fall 2024'
[taxonomies]
categories = ['Probability Theory']
tags = ['Probability Theory', 'Measure Theory', 'Sigma Algebras']
*/

== Week 1
<week-1>
=== Reading
<reading>
==== FT-1 | Probability Space
<ft-1-probability-space>
The purpose of probability is to obtain answers about real-life phenomena which do not have a predetermined outcome. We need a mathematical model to describe this so that we can provide answers to these questions. To this end, we define a #strong[probability space].

This space is defined on the #strong[sample space] of all possible outcomes of a random experiment, denoted as $Omega$. Each element (outcome) of $Omega$ is denoted by $omega$, and a collection of outcomes is called an #strong[event], aka a subset of $Omega$. Probability requires us to understand the size of an event. Not all subsets of $Omega$ can be measured, so we will define a collection of subsets on which a measure can be defined, the $sigma$#strong[\-algebra].

A set is described in braces like so:

${ x\|x upright(" satisfy property ") cal(P) }$

The set which does not contain an element is the empty set $nothing$.

To say that an element belongs to a set is that $omega in A$, and for it not to belong is $omega in.not A$.

A union of sets $A union B$ has elements that are in either of them.

An intersection of sets $A inter B$ has elements that are in both of them.

The complement $A^c$ of set $A$ is the set of elements in $Omega$ but not in $A$

The difference of two sets $A without B$ is the set of elements in $A$ but not $B$

The symmetric difference of two sets is $A Delta B =\(A without B\)union\(B without A\)$, which is the reverse of $A inter B$ if $A$ and $B$ share elements. In terms of a Venn diagram, it would be the left and right circle parts without the middle part.

If $A inter B = nothing$, then these sets are considered #strong[disjoint] or mutually exclusive.

There is a distributive law (DeMorgan's law) for intersection over union:

$A inter\(B union C\)=\(A inter B\)union\(A inter C\)$

and the reverse for unions.

Let's consider all possible subsets of $Omega$ as $cal(P)\(Omega\)$. An #strong[algebra] on $Omega$ is a collection of sets in $cal(P)\(Omega\)$ which is closed under complementarity and finite union.

There are three basic properties of the algebra $cal(A)$:

- $Omega in cal(A)$
- If $A in cal(A)$, then $A^c in cal(A)$
- If $A\,B in cal(A)$, then $A union B in cal(A)$

These properties naturally extend themselves to other properties, like the empty set being in the algebra, intersections being in the algebra, and the union of all different sets being in the algebra.

A $sigma$-algebra is a kind of algebra which is closed under countable unions. Regular algebras can have uncountable unions. These kinds of unions arise in stochastic processes. In order to use $sigma$-algebras when describing stochastic processes, we will define #strong[filtrations] that increase $sigma$-algebras over time. When we try to prove properties of $sigma$-algebras, we will instead prove properties about their generators, and then extend them to the $sigma$-algebra.

Let's consider a collection $cal(C)$ of sets in $Omega$. The $sigma$-algebra of $cal(C)$ defined as $sigma\(cal(C)\)$ has the properties that it contains all sets in $cal(C)$ and it is the smallest $sigma$-algebra which is a subset of any other $sigma$-algebra which contains $cal(C)$.

Here are some facts about $sigma$-algebras:

$cal(P)\(Omega\)$ is the largest possible $sigma$-algebra on $Omega$.

If $cal(C)$ is already a $sigma$-algebra, then the generated $sigma$-algebra is the same.

If $C$ is $nothing$ or $Omega$, $sigma\(cal(C)\)$ is ${ nothing\,Omega }$, the trivial $sigma$-algebra.

Any collection of sets which has $C$ has subset has the same $sigma$-algebra as $C$.

There are a lot of elements of $sigma$-algebras, so we typically consider them in the context of generator $cal(C)$.

A #strong[measurable space] is a pair $\(Omega\,cal(F)\)$ where $Omega$ is the sample space and $cal(F)$ is a $sigma$-algebra on $Omega$.

For two $sigma$-algebras $cal(F)_1$ and $cal(F)_2$, $cal(F)_1 inter cal(F)_2$ is a $sigma$-algebra (and in fact this can be generalized to any countable intersection of $sigma$-algebras, but $cal(F)_1 union cal(F)_2$ is not a $sigma$-algebra. You would have to define $sigma\(cal(F)_1 union cal(F)_2\)$, better denoted as $cal(F)_1 or cal(F)_2$.

To picture the #strong[Borel $sigma$-algebra], we must first envision our $Omega$ as a topological space where geometry is defined. We will specifically consider $Omega = bb(R)$, where our sample space is the real number line. The Borel $sigma$-algebra $cal(B)$ is generated by the class of open subsets of $Omega$. Think of this as every subdivision of the number line. Almost every subset of $bb(R)$ is in $cal(B)$, except for some very exotic sets.

As an example: if you partition $Omega$ i.e.~you split it into disjoint sets, the different unions of all those sets is the same as the $sigma$-algebra generated by all the disjoint sets. This can be proven by the fact that the complement of each collection of sets is present as a union of different sets, since they encompass the whole sample space.
