/*
title = "Probability Measures and Bayes' Rule"
date = 2024-09-09
source = 'FE-540 | Probability Theory'
source_date_basis = "Meeting date verified against the personal Academics calendar."
instructor = 'Zhenyu Cui'
term = 'Fall 2024'
[taxonomies]
categories = ['Probability Theory']
tags = ['Probability Theory', 'Conditional Probability', 'Bayes Rule']
*/

== Week 2
<week-2>
=== Reading
<reading>
==== FT-2 | Probability Measure
<ft-2-probability-measure>
We have already considered the measurable space $\(Omega\,cal(F)\)$ of the sample space and $sigma$-algebra. We can now define the probability measure $bb(P)$ as a measure defined on events in the $sigma$-algebra $cal(F)$, taking values in the unit interval $\[0\,1\]$. This measures the size of the events, which has two properties: the probability of $Omega$ is 1, which means that all outcomes are accounted for in the sample space, and that the measure is countably additive, which allows us to extend the probability of individual events to the entire $sigma$-algebra.

There are three ways of thinking on how the numerical values of probability manifest. Frequentism assigns values directly from data. Objectivism assigns values based on some model which is considered to describe aspects of the universe. Subjectivism characterizes probability as measuring beliefs about the world.

The definition of probability measure is as follows:

$bb(P)\(Omega\)= 1$

and for any sequence of disjoint events in $cal(F)$:

$bb(P)\(union.big_(n = 1)^oo A_n\)= sum_(n = 1)^oo bb(P)\(A_n\)$

There are some other basic properties that arise from these definitions:

When $A subset B$

$bb(P)\(B without A\)= bb(P)\(B\)- bb(P)\(A\)$

$bb(P)\(A\)lt.eq bb(P)\(B\)$

$bb(P)\(A^c\)= 1 - bb(P)\(A\)$

$bb(P)\(nothing\)= 0$

For all $A\,B$:

$bb(P)\(A union B\)= bb(P)\(A\)+ bb(P)\(B\)- P\(A inter B\)$

Poincaré's formula:

$bb(P)\(A_1 union A_2 union dots.h union A_n\)= sum_(I subset { 1\,2\,dots.h\,n })\(- 1\)^(\|I\|+ 1)bb(P)\(inter.big_(i in I) A_i\)$

$= sum_(i = 1)^n bb(P)\(A_i\)- sum_(i < j lt.eq n) bb(P)\(A_i inter A_j\)$

$+ sum_(i < j < k lt.eq n) bb(P)(A_i inter A_j inter A_k) - dots.h + (-1)^n times bb(P)(A_1 inter A_2 dots.h inter A_n)$

This is better expressed as the idea that the probability measure of the unions of sets can be expressed as the alternating signed partial sum of all the different partial intersections of the sequence of sets. It is proved by induction over the previous property.

Finite subadditivity (Boole's inequality):

$bb(P) (union.big_(i = 1)^n A_i) lt.eq sum_(i = 1)^n bb(P)\(A_i\)$

To show this, we shall set: $B_1 = A_1\,B_2 = A_2 inter A_1^c\,dots.h\,B_n = A_n inter A_(n - 1)^c inter dots.h inter A_1^c$

You can think of this every successive element being disjoint with all the previous elements, which means

$B_i inter B_j = nothing$

and also

$union.big_(i = 1)^n B_i = union.big_(i = 1)^n A_i$

because the union of all the disjoint parts of the sets will include all the overlap in the sets.

A #strong[partition] of a set $Omega$ is a collection of disjoint sets ${ Omega_i }$ where the union recreates the original set: $union.big_i Omega_i = Omega$

We can think of the probability of an event as the intersections of the event with a partition of $Omega$. This is #strong[the law of total probability]. For $\(A_i\)_(i in I)$ a partition of $Omega$ and every event $B in cal(F)$:

$bb(P)\(B\)= sum_(i in I) bb(P)\(B inter A_i\)$

===== Uniqueness of Probability Measures
<uniqueness-of-probability-measures>
Let's consider the idea of a $lambda$-system $cal(U)$ which is a family of events where:

$Omega in cal(U)$

For any $A\,B in cal(U)$ and $A subset B$, $B without A in cal(U)$

For a sequence of disjoint events $A_n$, indexed by $n in cal(U)$:

$union.big_n A_n in cal(U)$

You might notice that this is fairly similar to the definition of a $sigma$-algebra. In fact, a $sigma$-algebra is a $lambda$-system, and every $lambda$-system closed to finite intersection is a $sigma$-algebra.

Now let's consider a collection of sets $cal(M) subset.eq P\(Omega\)$ where $cal(U)\(cal(M)\)$ is the smallest $lambda$-system which contains $cal(M)$: $cal(U)\(cal(M)\)= sigma\(cal(M)\)$

Note that this is distinct from the previous definition because although the $lambda$-system is known to be a $sigma$-algebra, it is now also defined to be the same as one which is generated by the same collection of sets.

Now let's consider some probability measures $bb(P)_1$ and $bb(P)_2$ on the $sigma$-algebra $cal(F)$ generated from a collection of sets $cal(M)$. If $bb(P)_1$ and $bb(P)_2$ coincide on $cal(M)$, then they coincide on $cal(F)$. This means that for every event, the two probability measures assign the same probabilities, which includes all the different kinds of events generated by the $sigma$-algebra. This also applies to partitions of a sample space.

===== Monotone Class
<monotone-class>
This is a variant of a $lambda$-system. A #strong[monotone class $cal(M)$] of subsets in $Omega$ is closed under the formation of monotone unions and intersections, i.e.

$A_1\,A_2\,dots.h in cal(M)$ and $A_n subset.eq A_(n + 1)\,union_n A_n = A arrow.r.double A in cal(M)$

where the sets are increasing in size, containing the previous one,, and the union of all of them equals the last one.

$A_1\,A_2\,dots.h in cal(M)$ and $A_n supset.eq A_(n + 1) arrow.r.double inter_n A_n in cal(M)$

or where the sets are decreasing in size, containing the next one, and the intersection of all of them equals the last one.

#strong[Open question:] more stuff about monotone classes only if the professor talks about them.

===== Monotone Convergence Properties of Probability
<monotone-convergence-properties-of-probability>
How do we deal with infinity?

If $A_n\,A in cal(F)$ and $A_n arrow.t A$, which means that $A$ is a monotonically increasing class, then $bb(P)\(A_n\)arrow.t bb(P)\(A\)$ and the same is true for $A_n arrow.b A$.

Under countable subadditivity, the probability measure of the union of sets is less than or equal to the sum of the probability measures of those sets. That makes sense intuitively because it would be equal if the sets were disjoint, but the sets might overlap, making it less. We can use the above properties to extend this idea to countably infinite sets.

A #strong[null set] is a set with probability measure 0. $nothing$ is the obvious example, and in infinite sets there may be others like the probability measure of a singleton set in the Borel $sigma$-algebra.

===== Conditional Probability
<conditional-probability>
"In some cases the probability of an event happening depends not just on the experiment itself but on other information as well. #strong[Conditional probability] forms a framework in which this additional information can be incorporated."

$bb(P)\(A\|B\)= frac(bb(P)\(A inter B\), bb(P)\(B\))$

Obviously, the probability measure of $B$ cannot be 0, which makes sense because in order for something to be conditioned, the condition has to have happened, which is not possible if the probability is 0.

We can get the #strong[multiplicative rule] from this formula.

$bb(P)\(A inter B\)= bb(P)\(A\|B\)bb(P)\(B\)\,$

$bb(P)\(A inter B inter C\)= bb(P)\(A\|B inter C\)bb(P)\(B\|C\)bb(P)\(C\)$, etc.

Let's take an example. We have Urn 1 which contains 2 black balls and 3 white balls, and Urn 2 which contains 1 of each. One urn is chosen at random and one ball is chosen randomly from that urn. If a black ball is chosen, what is the probability it came from Urn 1?

Let's assign our variables.

$A$ is the event of choosing Urn 1, and $B$ is the event of choosing a black ball. We're trying to find $P\(A\|B\)$, so we need $P\(A inter B\)$. There are four total events in our sample space: { Urn1Black, Urn1White, Urn2Black, Urn2White }. The probability of Urn1Black is $0.5 times 0.4 = 0.2$. The probability of choosing a black ball is $0.5$ in the case of Urn 2 and $0.4$ in the case of Urn 1, which averages to $0.45$. So the overall probability is $0.2\/0.45$, which is $4\/9$.

The #strong[total probability formula] given $A_n$ partition of $Omega$ is

$bb(P)\(B\)= sum_(i = 1)^n bb(P)\(B\|A_i\)bb(P)\(A_i\)$

for any event $B in cal(F)$.

If Stanley wants to draw a card from 20, where 8 are favorable to him, what is the probability of him drawing a favorable card if he draws first, second, or third?

First is easy. $8\/20 = 0.4$

For second, there are two different possibilities. Either the first draw was a favorable or unfavorable card. Let's use the formula above.

$B$ is the event of Stanley drawing a favorable card. There are two $A$ events in consideration, which are the first card being favorable and unfavorable. $bb(P)\(A_1\)= 2\/5$ and $bb(P)\(A_2\)= 3\/5$. If a favorable card was drawn first, then the new probability is $7\/19$. Otherwise, it's $8\/19$. So the complete formula becomes

$bb(P)\(B\)= 2\/5 times 7\/19 + 3\/5 times 8\/19 = 0.4$

It's clear that the same situation would arise if he drew the third card.

#strong[Bayes' formula] is the following (like the others it's based on a partition $A$ and arbitrary set $B in cal(F)$):

$bb(P)\(A_j\|B\)= frac(bb(P)\(B\|A_j\)bb(P)\(A_j\), sum_(i = 1)^n bb(P)\(B\|A_i\)bb(P)\(A_i\))$

"This theorem can be interpreted as: All of a sudden we find out $B$ happened. In the light of this new information there should be a simple way to update all the probabilities of the sets in the partition $\(bb(P)\(A_j\|B\)\)$. Indeed, the Bayes rule provides just that."

So you take the existing $A$, and then condition it on $B$, and then the calculation cascades across the events in the sample space i.e.~$A$.

===== Independence
<independence>
Two events $A$ and $B$ are defined as #strong[independent] if

$bb(P)\(A inter B\)= bb(P)\(A\)bb(P)\(B\)$

which can be extended to the idea of being #strong[mutually independent] (or simply independent) for a set of events:

$bb(P) (union.big_(j in J) A_j) = product_(j in J) bb(P)\(A_j\)$

There's also the idea of #strong[jointly independent] (or pairwise independent):

$bb(P)\(A_i union A_j\)= bb(P)\(A_i\)bb(P)\(A_j\)$

which does not necessarily imply independence.

For two $sigma$-algebras $G$ and $H$, they are $bb(P)$-independent if

$bb(P)\(G union H\)= bb(P)\(G\)bb(P)\(H\)$

and the same applies for mutual independence as with events.

We can also show that if all $sigma$-algebras in a family are each generated from a collection of independent sets, they are independent. This independence is also associative. There's an additional property of "disassociativity of the independence", where independent families included in bigger independent families remain independent.

$sigma$-algebras generated by events are related in their independence.
